/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.PatientRole;

import Business.EcoSystem;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.Hashtable;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author bardw_000
 */
public class ConfirmJPanel extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    private EcoSystem system;
    private UserAccount doctoruseraccount;
    private UserAccount patientuseraccount;

    /**
     * Creates new form ConfirmJPanel
     */
    public ConfirmJPanel(JPanel upc, EcoSystem system, UserAccount doctoruseraccount, UserAccount patientuseraccount) {
        initComponents();
        this.userProcessContainer = upc;
        this.system = system;
        this.doctoruseraccount = doctoruseraccount;
        this.patientuseraccount = patientuseraccount;
        
        populateTextArea();
    }

    private void populateTextArea(){
        Hashtable<UserAccount, String> conclusionhashtable = this.doctoruseraccount.getDoctoraccount().getConclusionHashtable();
        String conclusion = conclusionhashtable.get(this.patientuseraccount);
        if(conclusion == null){
            conclusion = "N/A";
        }
        this.ConclusionTextArea.setText(conclusion);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        starComboBox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        closeComboBox = new javax.swing.JComboBox();
        finishBtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ConclusionTextArea = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();

        jLabel2.setText("How do you rate this doctor?");

        starComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "5 Star", "4 Star", "3 Star", "2 Star", "1 Star", "No Comment" }));

        jLabel3.setText("Do you want to close this conversation?");

        closeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Yes", "No" }));

        finishBtn.setText("Finish");
        finishBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishBtnActionPerformed(evt);
            }
        });

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        ConclusionTextArea.setEditable(false);
        ConclusionTextArea.setColumns(20);
        ConclusionTextArea.setRows(5);
        jScrollPane1.setViewportView(ConclusionTextArea);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Conclusion");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(144, 144, 144)
                                .addComponent(finishBtn))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(closeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(108, 108, 108)
                                    .addComponent(starComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jButton2)))
                .addContainerGap(175, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel4)
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(starComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(closeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(finishBtn)
                .addGap(36, 36, 36)
                .addComponent(jButton2)
                .addContainerGap(184, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void finishBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishBtnActionPerformed
        // TODO add your handling code here:
        String star = (String) this.starComboBox.getSelectedItem();
        String choice = (String) this.closeComboBox.getSelectedItem();
        int starNum = 0;
        if(star.equals("5 Star")){
            starNum = 5;
        }else if(star.equals("4 Star")){
            starNum = 4;
        }else if(star.equals("3 Star")){
            starNum = 3;
        }else if(star.equals("2 Star")){
            starNum = 2;
        }else if(star.equals("1 Star")){
            starNum = 1;
        }else{
            starNum = -1;
        }

        
        if(choice.equals("Yes")){
           if(starNum != -1){
           this.doctoruseraccount.getDoctoraccount().increment();
           this.doctoruseraccount.getDoctoraccount().addStar(starNum);
           }
            
           this.doctoruseraccount.getDoctoraccount().getStatusHashtable().put(this.patientuseraccount, "Closed");
           Hashtable<UserAccount, String> conclusionhashtable = this.doctoruseraccount.getDoctoraccount().getConclusionHashtable();
           conclusionhashtable.put(this.patientuseraccount, "");
           JOptionPane.showMessageDialog(null, "You have finished the conversion. Thank you for your participation!");
        }
        
        userProcessContainer.removeAll();
        PatientWorkAreaJPanel patientWorkAreaJPanel = new PatientWorkAreaJPanel(userProcessContainer, system, this.patientuseraccount);
        userProcessContainer.add("PatientWorkAreaJPanel", patientWorkAreaJPanel);
        CardLayout cardlayout = (CardLayout) userProcessContainer.getLayout();
        cardlayout.next(userProcessContainer);
    }//GEN-LAST:event_finishBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea ConclusionTextArea;
    private javax.swing.JComboBox closeComboBox;
    private javax.swing.JButton finishBtn;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox starComboBox;
    // End of variables declaration//GEN-END:variables
}
