/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.PatientRole;

import Business.Drug.DrugReceived;
import Business.EcoSystem;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.Hashtable;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author bardw_000
 */
public class DecideBuyJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem system;
    private UserAccount doctoruseraccount;
    private UserAccount patientuseraccount;
    private String totalamount;
    
    /**
     * Creates new form DecideBuyJPanel
     */
    public DecideBuyJPanel(JPanel upc, EcoSystem system, UserAccount doctoruseraccount, UserAccount patientuseraccount, String totalamount) {
        initComponents();
        this.userProcessContainer = upc;
        this.system = system;
        this.doctoruseraccount = doctoruseraccount;
        this.patientuseraccount = patientuseraccount;
        this.totalamount = totalamount;
        
        populateForm();
    }
    
    private void populateForm(){
        
        if(this.patientuseraccount.getPatientaccount().getAddress() != null){
        this.addressTxt.setText(this.patientuseraccount.getPatientaccount().getAddress());
        this.cityTxt.setText(this.patientuseraccount.getPatientaccount().getCity());
        this.zipcodeTxt.setText(this.patientuseraccount.getPatientaccount().getZipcode());
        this.phonenumberTxt.setText(this.patientuseraccount.getPatientaccount().getPhonenumber());
        this.creditcardTxt.setText(this.patientuseraccount.getPatientaccount().getCreditcardnumber());
        this.csvTxt.setText(this.patientuseraccount.getPatientaccount().getCsvnumber());
        }
        this.totalamountTxt.setText(this.totalamount);
    }

    private void setPatientData(){
        this.patientuseraccount.getPatientaccount().setAddress(this.addressTxt.getText());
        this.patientuseraccount.getPatientaccount().setCity(this.cityTxt.getText());
        this.patientuseraccount.getPatientaccount().setZipcode(this.zipcodeTxt.getText());
        this.patientuseraccount.getPatientaccount().setPhonenumber(this.phonenumberTxt.getText());
        this.patientuseraccount.getPatientaccount().setCreditcardnumber(this.creditcardTxt.getText());
        this.patientuseraccount.getPatientaccount().setCsvnumber(this.csvTxt.getText());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        addressTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cityTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        phonenumberTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        totalamountTxt = new javax.swing.JTextField();
        confirmBtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        creditcardTxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        csvTxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        zipcodeTxt = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Please type your Information");

        jLabel2.setText("Address");

        jLabel3.setText("City");

        jLabel4.setText("Phone Number");

        jLabel5.setText("The Total Amount:");

        totalamountTxt.setEditable(false);

        confirmBtn.setText("Confirm");
        confirmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmBtnActionPerformed(evt);
            }
        });

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setText("Credit Card Number");

        jLabel7.setText("CSV Number");

        jLabel8.setText("ZipCode");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(75, 75, 75)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(addressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(phonenumberTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cityTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(totalamountTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                        .addComponent(csvTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(zipcodeTxt, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(creditcardTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(confirmBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jButton2)))
                .addContainerGap(326, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel1)
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(addressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(zipcodeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(phonenumberTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(creditcardTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(csvTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(totalamountTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(confirmBtn)
                .addGap(46, 46, 46)
                .addComponent(jButton2)
                .addContainerGap(266, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void confirmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmBtnActionPerformed
        // TODO add your handling code here:
        if(addressTxt.getText().length() == 0){
        JOptionPane.showMessageDialog(null, "Missing addressTxt!");
        return;
        }
        if(cityTxt.getText().length() == 0){
        JOptionPane.showMessageDialog(null, "Missing cityTxt!");
        return;
        }
        if(!zipcodeTxt.getText().matches("^\\d+$")){
        JOptionPane.showMessageDialog(null, "Please type an integer for zipcodeTxt!");
        return;
        }
        if(!phonenumberTxt.getText().matches("^\\d+$")){
        JOptionPane.showMessageDialog(null, "Please type an integer for phonenumberTxt!");
        return;
        }
        if(!creditcardTxt.getText().matches("^\\d+$")){
        JOptionPane.showMessageDialog(null, "Please type an integer for creditcardTxt!");
        return;
        }
        if(!csvTxt.getText().matches("^\\d+$")){
        JOptionPane.showMessageDialog(null, "Please type an integer for csvTxt!");
        return;
        }
        
        setPatientData();
        this.totalamountTxt.setText(totalamount);
        Hashtable<UserAccount, ArrayList<DrugReceived>> drughashtable = this.doctoruseraccount.getDoctoraccount().getDrugHashtable();
        drughashtable.put(this.patientuseraccount, new ArrayList<DrugReceived>());
        JOptionPane.showMessageDialog(null, "Thank you for your payment!");
        ConfirmJPanel confirmJPanel = new ConfirmJPanel(userProcessContainer, system, this.doctoruseraccount, this.patientuseraccount);      
        userProcessContainer.add("ConfirmJPanel", confirmJPanel);      
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_confirmBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressTxt;
    private javax.swing.JTextField cityTxt;
    private javax.swing.JButton confirmBtn;
    private javax.swing.JTextField creditcardTxt;
    private javax.swing.JTextField csvTxt;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField phonenumberTxt;
    private javax.swing.JTextField totalamountTxt;
    private javax.swing.JTextField zipcodeTxt;
    // End of variables declaration//GEN-END:variables
}
