/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.PatientRole;

import Business.EcoSystem;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.Hashtable;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author bardw_000
 */
public class PatientChatJPanel extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    private EcoSystem system;
    private UserAccount patientuseraccount;
    private UserAccount doctoruseraccount;
    private Hashtable<UserAccount, ArrayList<String>> hashtable;
    private ArrayList<String> messages;

    /**
     * Creates new form ChatJPanel
     */
    public PatientChatJPanel(JPanel upc, EcoSystem system, UserAccount patientuseraccount, UserAccount doctoruseraccount) {
        initComponents();
        this.userProcessContainer = upc;
        this.system = system;
        this.patientuseraccount = patientuseraccount;
        this.doctoruseraccount = doctoruseraccount;
        this.hashtable = this.doctoruseraccount.getDoctoraccount().getHashtable();
        this.messages = this.hashtable.get(patientuseraccount);
        
        this.doctorNameTxt.setText(doctoruseraccount.getName());
        populateMessageArea();
    }

    private void populateMessageArea(){
        
        String allmessages = "";
        if(messages != null){
        for(String message: messages){
            allmessages = allmessages + message + "\n";
            }
        this.chatTextArea.setText(allmessages);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        chatTextArea = new javax.swing.JTextArea();
        sendBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        chatTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        doctorNameTxt = new javax.swing.JTextField();
        NextBtn = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("To chat with your doctor");

        chatTextArea.setColumns(20);
        chatTextArea.setFont(new java.awt.Font("Monospaced", 0, 15)); // NOI18N
        chatTextArea.setRows(5);
        jScrollPane1.setViewportView(chatTextArea);

        sendBtn.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        sendBtn.setText("Send Message");
        sendBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendBtnActionPerformed(evt);
            }
        });

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        chatTxt.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel2.setText("Doctor Name:");

        doctorNameTxt.setEditable(false);
        doctorNameTxt.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        NextBtn.setText("Next");
        NextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(38, 38, 38)
                                .addComponent(doctorNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButton1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(NextBtn))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(chatTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(sendBtn))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(591, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(doctorNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chatTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sendBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(NextBtn))
                .addContainerGap(261, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void sendBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendBtnActionPerformed
        // TODO add your handling code here:
        String message = this.patientuseraccount.getName() + ": " + this.chatTxt.getText();
        message = splitmessage(message);        
        if(this.messages == null){
            this.messages = new ArrayList<String>();
            this.hashtable.put(patientuseraccount, messages);
            this.messages.add(message);
        }else{
            this.messages.add(message);      
        }
        this.chatTxt.setText("");
        
        // to set the patient status to open
        this.doctoruseraccount.getDoctoraccount().getStatusHashtable().put(this.patientuseraccount, "Open");
        /*
        if(this.patientuseraccount.getPatientaccount().getStatus().equals("Closed")){
        this.patientuseraccount.getPatientaccount().setStatus("Open");
        }
        */
        populateMessageArea();
    }//GEN-LAST:event_sendBtnActionPerformed

    // to split the message
    private String splitmessage(String message){
        String finalmessage = message;
        int length = message.length();
        for(int i = 50; i < length; i = i + 50){
            finalmessage = new StringBuilder(finalmessage).insert(i, "\n").toString();
        }
        return finalmessage;
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void NextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextBtnActionPerformed
        // TODO add your handling code here:
        String status = this.doctoruseraccount.getDoctoraccount().getStatusHashtable().get(this.patientuseraccount);
        if(status.equals("Finished")){
            PatientMedicationJPanel patientMedicationJPanel = new PatientMedicationJPanel(userProcessContainer, system, this.doctoruseraccount, this.patientuseraccount);      
            userProcessContainer.add("PatientMedicationJPanel", patientMedicationJPanel);      
            CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
            cardLayout.next(userProcessContainer);
        }else{
            JOptionPane.showMessageDialog(null, "You cannot continue, please wait for your doctor!");
        }    
    }//GEN-LAST:event_NextBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton NextBtn;
    private javax.swing.JTextArea chatTextArea;
    private javax.swing.JTextField chatTxt;
    private javax.swing.JTextField doctorNameTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton sendBtn;
    // End of variables declaration//GEN-END:variables
}
