/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.PatientRole;

import Business.Drug.DrugReceived;
import Business.EcoSystem;
import Business.UserAccount.UserAccount;
import Interface.DrugAdminRole.ViewDrugJPanel;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.Hashtable;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bardw_000
 */
public class PatientMedicationJPanel extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    private EcoSystem system;
    private UserAccount doctoruseraccount;
    private UserAccount patientuseraccount;
    private Hashtable<UserAccount, ArrayList<DrugReceived>> drugHashtable;

    /**
     * Creates new form PatientMedicationJPanel
     */
    public PatientMedicationJPanel(JPanel upc, EcoSystem system, UserAccount doctoruseraccount, UserAccount patientuseraccount) {
        initComponents();
        this.userProcessContainer = upc;
        this.system = system;
        this.doctoruseraccount = doctoruseraccount;
        this.patientuseraccount = patientuseraccount;
        
        populateDrugSelectTable();
    }

    private void populateDrugSelectTable(){       
        this.drugHashtable = this.doctoruseraccount.getDoctoraccount().getDrugHashtable();
        ArrayList<DrugReceived> druglist = this.drugHashtable.get(this.patientuseraccount);
        if(this.drugHashtable.get(this.patientuseraccount) == null){
            this.drugHashtable.put(this.patientuseraccount, new ArrayList<DrugReceived>());
            druglist = this.drugHashtable.get(this.patientuseraccount);
        }
        
        DefaultTableModel dtm = (DefaultTableModel)this.drugSelectTable.getModel();
        int rowCount = this.drugSelectTable.getRowCount();
        for(int i = rowCount - 1; i >= 0; i--){
            dtm.removeRow(i);
        }
        
        int totalamount = 0;
        for(DrugReceived drug: druglist){
            Object row[] = new Object[4];
            row[0] = drug;
            row[1] = drug.getDrug().getName();
            row[2] = drug.getQuantity();
            row[3] = drug.getDrug().getPrice() + "$";
            totalamount = totalamount + drug.getQuantity() * drug.getDrug().getPrice();
            dtm.addRow(row);
        }       
        this.totalTxt.setText(String.valueOf(totalamount) + "$");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nextBtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        drugSelectTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        totalTxt = new javax.swing.JTextField();
        viewDetailBtn = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Recommand Medication");

        nextBtn.setText("Next");
        nextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBtnActionPerformed(evt);
            }
        });

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        drugSelectTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Serial Number", "Drug Name", "Quantity", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(drugSelectTable);

        jLabel2.setText("Total Amount:");

        totalTxt.setEditable(false);

        viewDetailBtn.setText("View Detail");
        viewDetailBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDetailBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nextBtn))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(totalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(viewDetailBtn))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(376, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(totalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewDetailBtn))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(nextBtn))
                .addContainerGap(247, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void nextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBtnActionPerformed
        // TODO add your handling code here:
        if(this.totalTxt.getText().equals("0$")){
        ConfirmJPanel confirmJPanel = new ConfirmJPanel(userProcessContainer, system, this.doctoruseraccount, this.patientuseraccount);      
        userProcessContainer.add("ConfirmJPanel", confirmJPanel);      
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);
        }else{
        DecisionJPanel decisionJPanel = new DecisionJPanel(userProcessContainer, system, this.doctoruseraccount, this.patientuseraccount, this.totalTxt.getText());      
        userProcessContainer.add("DecisionJPanel", decisionJPanel);      
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);
        }
    }//GEN-LAST:event_nextBtnActionPerformed

    private void viewDetailBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDetailBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = this.drugSelectTable.getSelectedRow();
        if(selectedRow >= 0){
        DrugReceived drugreceived = (DrugReceived)drugSelectTable.getValueAt(selectedRow, 0);
        ViewDrugJPanel viewDrugJPanel = new ViewDrugJPanel(userProcessContainer, drugreceived.getDrug());      
        userProcessContainer.add("ViewDrugJPanel", viewDrugJPanel);      
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);        
        }else{
            JOptionPane.showMessageDialog(null, "Please select a row from the table first.", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_viewDetailBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable drugSelectTable;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton nextBtn;
    private javax.swing.JTextField totalTxt;
    private javax.swing.JButton viewDetailBtn;
    // End of variables declaration//GEN-END:variables
}
