/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.DoctorRole;

import Business.Drug.DrugReceived;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.HospitalEnterprise;
import Business.UserAccount.UserAccount;
import Interface.DrugAdminRole.ViewDrugJPanel;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.Hashtable;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bardw_000
 */
public class SelectMedicationJPanel extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    private EcoSystem system;
    private Enterprise enterprise;
    private UserAccount patientuseraccount;
    private UserAccount doctoruseraccount;
    private Hashtable<UserAccount, ArrayList<DrugReceived>> drugHashtable;

    /**
     * Creates new form SelectMedicationJPanel
     */
    public SelectMedicationJPanel(JPanel upc, EcoSystem system, UserAccount patientuseraccount, UserAccount doctoruseraccount, Enterprise enterprise) {
        initComponents();
        
        this.userProcessContainer = upc;
        this.system = system;
        this.enterprise = enterprise;
        this.patientuseraccount = patientuseraccount;
        this.doctoruseraccount = doctoruseraccount;
        populateInventoryTable();
        populateDrugSelectTable();
    }
    
    private void populateInventoryTable(){
        HospitalEnterprise he = (HospitalEnterprise) this.enterprise;
        
        DefaultTableModel dtm = (DefaultTableModel)drugInventoryTable.getModel();
        int rowCount = drugInventoryTable.getRowCount();
        for(int i = rowCount - 1; i >= 0; i--){
            dtm.removeRow(i);
        }
        
        for(DrugReceived drug: he.getDruginventory().getReceviedDrugList()){
            Object row[] = new Object[4];
            row[0] = drug;
            row[1] = drug.getDrug().getName();
            row[2] = drug.getQuantity();
            row[3] = drug.getDrug().getPrice() + "$";
            dtm.addRow(row);
        }
    }
    
    private void populateDrugSelectTable(){       
        this.drugHashtable = this.doctoruseraccount.getDoctoraccount().getDrugHashtable();
        ArrayList<DrugReceived> druglist = this.drugHashtable.get(this.patientuseraccount);
        if(this.drugHashtable.get(this.patientuseraccount) == null){
            this.drugHashtable.put(this.patientuseraccount, new ArrayList<DrugReceived>());
            druglist = this.drugHashtable.get(this.patientuseraccount);
        }
        
        DefaultTableModel dtm = (DefaultTableModel)this.drugSelectTable.getModel();
        int rowCount = this.drugSelectTable.getRowCount();
        for(int i = rowCount - 1; i >= 0; i--){
            dtm.removeRow(i);
        }
        
        int totalamount = 0;
        for(DrugReceived drug: druglist){
            Object row[] = new Object[4];
            row[0] = drug;
            row[1] = drug.getDrug().getName();
            row[2] = drug.getQuantity();
            row[3] = drug.getDrug().getPrice() + "$";
            totalamount = totalamount + drug.getQuantity() * drug.getDrug().getPrice();
            dtm.addRow(row);
        }       
        this.totalTxt.setText(String.valueOf(totalamount) + "$");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        addDrugBtn = new javax.swing.JButton();
        removeBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        quantityTxt = new javax.swing.JTextField();
        nextBtn = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        drugSelectTable = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        drugInventoryTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        totalTxt = new javax.swing.JTextField();
        viewDetailBtn = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Select Drugs from Drug Inventory");

        addDrugBtn.setText("Add");
        addDrugBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDrugBtnActionPerformed(evt);
            }
        });

        removeBtn.setText("Remove");
        removeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBtnActionPerformed(evt);
            }
        });

        jLabel3.setText("Quantity");

        nextBtn.setText("Next");
        nextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBtnActionPerformed(evt);
            }
        });

        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        drugSelectTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Serial Number", "Drug Name", "Quantity", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(drugSelectTable);

        drugInventoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Serial Number", "Drug Name", "Quantity", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(drugInventoryTable);

        jLabel2.setText("Total Amount:");

        totalTxt.setEditable(false);

        viewDetailBtn.setText("View Detail");
        viewDetailBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDetailBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(totalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(removeBtn))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nextBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(viewDetailBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(quantityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(addDrugBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(506, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addDrugBtn)
                            .addComponent(jLabel3)
                            .addComponent(quantityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(viewDetailBtn)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(removeBtn)
                    .addComponent(jLabel2)
                    .addComponent(totalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nextBtn)
                    .addComponent(jButton4))
                .addContainerGap(195, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addDrugBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDrugBtnActionPerformed
        // TODO add your handling code here:
        
        if(!this.quantityTxt.getText().matches("^\\d+$")){
        JOptionPane.showMessageDialog(null, "Please type a integer for priceTextField!");
        return;
        }        
        
        int selectedRow = drugInventoryTable.getSelectedRow();
        if(selectedRow >= 0){
            DrugReceived drug = (DrugReceived)drugInventoryTable.getValueAt(selectedRow, 0);
            int quantity = Integer.parseInt(this.quantityTxt.getText());
            if(quantity <= 0){
                JOptionPane.showMessageDialog(null, "Input wrong number!", "Warning", JOptionPane.WARNING_MESSAGE);
                return;
            }else if(drug.getQuantity() < quantity){
                JOptionPane.showMessageDialog(null, "Not enough drug!", "Warning", JOptionPane.WARNING_MESSAGE);
                return;
            }else{
            drug.setQuantity(drug.getQuantity() - quantity);
            ArrayList<DrugReceived> drugs = this.drugHashtable.get(this.patientuseraccount);          
            DrugReceived drugSelected = new DrugReceived();
            drugSelected.setDrug(drug.getDrug());
            drugSelected.setSerialNumber(drug.getSerialNumber());
            drugSelected.setQuantity(quantity);
            drugSelected.setExpirationDate(drug.getExpirationDate());        
            drugs.add(drugSelected);
            this.drugHashtable.put(this.patientuseraccount, drugs);
            
            this.populateInventoryTable();
            this.populateDrugSelectTable();
            this.quantityTxt.setText("");
            }
            
        }else{
            JOptionPane.showMessageDialog(null, "Please select a row from the table first.", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_addDrugBtnActionPerformed

    private void removeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = drugSelectTable.getSelectedRow();
        if(selectedRow >= 0){
            DrugReceived drugSelected = (DrugReceived)drugSelectTable.getValueAt(selectedRow, 0);
            ArrayList<DrugReceived> drugsSelected = this.drugHashtable.get(this.patientuseraccount);
            drugsSelected.remove(drugSelected);
            
            HospitalEnterprise he = (HospitalEnterprise) this.enterprise;
            for(DrugReceived drug: he.getDruginventory().getReceviedDrugList()){
            int quantity = drugSelected.getQuantity();
            if(drug.getSerialNumber().equals(drugSelected.getSerialNumber())){
                drug.setQuantity(quantity + drug.getQuantity());
                break;
                }
            }
            this.populateInventoryTable();
            this.populateDrugSelectTable();
        }else{
            JOptionPane.showMessageDialog(null, "Please select a row from the table first.", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_removeBtnActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void nextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBtnActionPerformed
        // TODO add your handling code here:
        DoctorFinishJPanel doctorFinishJPanel = new DoctorFinishJPanel(userProcessContainer, system, enterprise, doctoruseraccount, patientuseraccount);      
        userProcessContainer.add("DoctorFinishJPanel", doctorFinishJPanel);      
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_nextBtnActionPerformed

    private void viewDetailBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDetailBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = drugInventoryTable.getSelectedRow();
        if(selectedRow >= 0){
        DrugReceived drugreceived = (DrugReceived)drugInventoryTable.getValueAt(selectedRow, 0);
        ViewDrugJPanel viewDrugJPanel = new ViewDrugJPanel(userProcessContainer, drugreceived.getDrug());      
        userProcessContainer.add("ViewDrugJPanel", viewDrugJPanel);      
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);        
        }else{
            JOptionPane.showMessageDialog(null, "Please select a row from the table first.", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_viewDetailBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addDrugBtn;
    private javax.swing.JTable drugInventoryTable;
    private javax.swing.JTable drugSelectTable;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton nextBtn;
    private javax.swing.JTextField quantityTxt;
    private javax.swing.JButton removeBtn;
    private javax.swing.JTextField totalTxt;
    private javax.swing.JButton viewDetailBtn;
    // End of variables declaration//GEN-END:variables
}
