/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.DrugAdminRole;

import Business.Drug.Drug;
import Business.Drug.DrugInventory;
import Business.Drug.DrugReceived;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author bardw_000
 */
public class CreateDrugInventoryJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Drug drug;
    private DrugInventory drugInventory;
    
    /**
     * Creates new form CreateDrugInventory
     */
    public CreateDrugInventoryJPanel(JPanel upc, Drug drug, DrugInventory drugInventory) {
        initComponents();
        
        this.userProcessContainer = upc;
        this.drug = drug;
        this.drugInventory = drugInventory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        serialNumberTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        expirationDateTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        quantityTextField = new javax.swing.JTextField();
        addDrugBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Add Additional Drugs");

        jLabel2.setText("Serial Number");

        jLabel3.setText("Expiration Date");

        jLabel4.setText("Quantity");

        addDrugBtn.setText("Add");
        addDrugBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDrugBtnActionPerformed(evt);
            }
        });

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(70, 70, 70)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(serialNumberTextField)
                            .addComponent(expirationDateTextField)
                            .addComponent(quantityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addComponent(addDrugBtn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jButton1)))
                .addContainerGap(183, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(serialNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(expirationDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(quantityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(addDrugBtn)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(195, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void addDrugBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDrugBtnActionPerformed
        // TODO add your handling code here:
        
        if(serialNumberTextField.getText().length() == 0){
        JOptionPane.showMessageDialog(null, "Missing serialNumberTextField!");
        return;
        }
        if(expirationDateTextField.getText().length() == 0){
        JOptionPane.showMessageDialog(null, "Missing expirationDateTextField!");
        return;
        }
        if(!quantityTextField.getText().matches("^\\d+$")){
        JOptionPane.showMessageDialog(null, "Please type a integer for quantityTextField!");
        return;
        }
        
        DrugReceived d = drugInventory.addDrug();
        d.setDrug(this.drug);
        d.setSerialNumber(this.serialNumberTextField.getText());
        d.setExpirationDate(this.expirationDateTextField.getText());
        d.setQuantity(Integer.parseInt(this.quantityTextField.getText()));
        
        resetFields();
        
        JOptionPane.showMessageDialog(null, "You have added the drug successfully!");
    }//GEN-LAST:event_addDrugBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this); 
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.previous(userProcessContainer);
        
        refreshTable();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void refreshTable() {
        int index = userProcessContainer.getComponentCount() - 1;
        ManageDrugInventoryJPanel panel = (ManageDrugInventoryJPanel) userProcessContainer.getComponent(index);
        panel.populateDrugInventoryTable();
        panel.setAreaText();
    }
    
    private void resetFields(){
        this.serialNumberTextField.setText("");
        this.expirationDateTextField.setText("");
        this.quantityTextField.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addDrugBtn;
    private javax.swing.JTextField expirationDateTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField quantityTextField;
    private javax.swing.JTextField serialNumberTextField;
    // End of variables declaration//GEN-END:variables
}
