/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Register;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Role.DoctorRole;
import Business.UserAccount.DoctorAccount;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author bardw_000
 */
public class DoctorRegisterJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem system;
    private Network network;
    private Enterprise enterprise;
    
    /**
     * Creates new form DoctorRegisterJPanel
     */
    public DoctorRegisterJPanel(JPanel upc, EcoSystem system, Network network, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = upc;
        this.system = system;
        this.network = network;
        this.enterprise = enterprise;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        usernameTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        passwordTxt = new javax.swing.JPasswordField();
        createBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        backgroundTxt = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        yearCombobox = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        universityTxt = new javax.swing.JTextField();
        degreeCombobox = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        nameTxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        ageTxt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        concentrationTxt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        phoneTxt = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Doctor Register Account");

        jLabel2.setText("Username");

        jLabel3.setText("Password");

        createBtn.setText("Create");
        createBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBtnActionPerformed(evt);
            }
        });

        jLabel4.setText("Background");

        backgroundTxt.setColumns(20);
        backgroundTxt.setRows(5);
        jScrollPane1.setViewportView(backgroundTxt);

        jLabel5.setText("Years of experience");

        yearCombobox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1 year", "2 years", "3-5 years", "more than 5 years" }));

        jLabel6.setText("University");

        jLabel7.setText("Degree");

        degreeCombobox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bachelor", "Master", "Doctor" }));

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel8.setText("Name");

        jLabel9.setText("Age");

        jLabel10.setText("Concentration");

        jLabel11.setText("Phone Number");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel11))
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(universityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(degreeCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yearCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(phoneTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(passwordTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(usernameTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                                .addComponent(nameTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ageTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(concentrationTxt, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(createBtn))))
                .addContainerGap(192, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel1)
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(usernameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(passwordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(ageTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(phoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(concentrationTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(universityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(degreeCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(yearCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(createBtn)
                .addGap(43, 43, 43)
                .addComponent(jButton1)
                .addContainerGap(212, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void createBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBtnActionPerformed
        // TODO add your handling code here:
        if(usernameTxt.getText().length() == 0){
        JOptionPane.showMessageDialog(null, "Missing usernameTxt!");
        return;
        }else if(passwordTxt.getPassword().length == 0){
        JOptionPane.showMessageDialog(null, "Missing passwordTxt!");
        return;
        }else if(nameTxt.getText().length() == 0){
        JOptionPane.showMessageDialog(null, "Missing nameTxt!");
        return;
        }else if(!ageTxt.getText().matches("^\\d+$")){
        JOptionPane.showMessageDialog(null, "Please type an interger for ageTxt!");
        return;
        }else if(!phoneTxt.getText().matches("^\\d+$")){
        JOptionPane.showMessageDialog(null, "Please type an interger for phoneTxt!");
        return;
        }else if(concentrationTxt.getText().length() == 0){
        JOptionPane.showMessageDialog(null, "Missing concentrationTxt!");
        return;
        }else if(finduseraccount(system, usernameTxt.getText())){
        JOptionPane.showMessageDialog(null, "The username has already existed!");
        return;    
        }else if(universityTxt.getText().length() == 0){
        JOptionPane.showMessageDialog(null, "Missing universityTxt!");
        return;
        }else if(backgroundTxt.getText().length() == 0){
        JOptionPane.showMessageDialog(null, "Missing backgroundTxt!");
        return;
        }
        
        UserAccount ua = this.system.getUserAccountDirectory().createUserAccount(
                usernameTxt.getText(), String.valueOf(passwordTxt.getPassword()), new DoctorRole(), network, enterprise);
        ua.setName(this.nameTxt.getText());
        ua.setAge(this.ageTxt.getText());
        DoctorAccount da = new DoctorAccount();
        da.setPhonenumber(this.phoneTxt.getText());
        da.setConcentration(this.concentrationTxt.getText());
        da.setBackground(this.backgroundTxt.getText());
        da.setDegree((String)this.degreeCombobox.getSelectedItem());
        da.setUniversity(this.universityTxt.getText());
        da.setYearsofexperience((String)this.yearCombobox.getSelectedItem());
        ua.setDoctoraccount(da);
        JOptionPane.showMessageDialog(null, "You have created the doctor account successfully!");
        disableForm();
        
    }//GEN-LAST:event_createBtnActionPerformed

    // to disable all the forms
    private void disableForm(){
        this.usernameTxt.setText("");
        this.passwordTxt.setText("");
        this.nameTxt.setText("");
        this.ageTxt.setText("");
        this.phoneTxt.setText("");
        this.concentrationTxt.setText("");
        this.backgroundTxt.setText("");
        this.universityTxt.setText("");
        
    }
    
    // to check if the username exists in the account list
     private boolean finduseraccount(EcoSystem system, String username) {
         for(UserAccount useraccount: system.getUserAccountDirectory().getUserAccountList()){
             if(useraccount.getUsername().equals(username)){
                 return true;
             }
         }
         return false;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ageTxt;
    private javax.swing.JTextArea backgroundTxt;
    private javax.swing.JTextField concentrationTxt;
    private javax.swing.JButton createBtn;
    private javax.swing.JComboBox degreeCombobox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JPasswordField passwordTxt;
    private javax.swing.JTextField phoneTxt;
    private javax.swing.JTextField universityTxt;
    private javax.swing.JTextField usernameTxt;
    private javax.swing.JComboBox yearCombobox;
    // End of variables declaration//GEN-END:variables
}
