/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.AdministrativeRole;

import Business.EcoSystem;
import Business.Organization.Organization;
import Business.Role.AdminRole;
import Business.Role.DrugAdminRole;
import Business.Role.HRManagerRole;
import Business.Role.ManagerRole;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author bardw_000
 */
public class AddNewUserAccountJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem system;
    private Organization organization;
    private String role;
    
    /**
     * Creates new form AddNewUserAccountJPanel
     */
    public AddNewUserAccountJPanel(JPanel upc, EcoSystem system, Organization organization, String role) {
        initComponents();
        this.userProcessContainer = upc;
        this.system = system;
        this.organization = organization;
        this.role = role;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        usernameTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nameTxt = new javax.swing.JTextField();
        ageTxt = new javax.swing.JTextField();
        submitBtn = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        passwordTxt = new javax.swing.JPasswordField();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Add New UserAccount");

        jLabel2.setText("Username");

        jLabel3.setText("Password");

        jLabel4.setText("Name");

        jLabel5.setText("Age");

        submitBtn.setText("Submit");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });

        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addComponent(submitBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(89, 89, 89)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(usernameTxt)
                            .addComponent(nameTxt)
                            .addComponent(ageTxt)
                            .addComponent(passwordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jButton4)))
                .addContainerGap(470, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(usernameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(passwordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ageTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(102, 102, 102)
                .addComponent(submitBtn)
                .addGap(62, 62, 62)
                .addComponent(jButton4)
                .addContainerGap(192, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.previous(userProcessContainer);
        
        refreshTable();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void refreshTable() {
        int index = userProcessContainer.getComponentCount() - 1;
        UserAccountListJPanel panel = (UserAccountListJPanel) userProcessContainer.getComponent(index);
        panel.populateTable();
    }
    
    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        // TODO add your handling code here:
        if(usernameTxt.getText().length() == 0){
        JOptionPane.showMessageDialog(null, "Missing usernameTxt!");
        return;
        }else if(passwordTxt.getPassword().length == 0){
        JOptionPane.showMessageDialog(null, "Missing passwordTxt!");
        return;
        }else if(nameTxt.getText().length() == 0){
        JOptionPane.showMessageDialog(null, "Missing nameTxt!");
        return;
        }else if(!ageTxt.getText().matches("^\\d+$")){
        JOptionPane.showMessageDialog(null, "Please type an integer for ageTxt!");
        return;
        }else if(finduseraccount(this.system, usernameTxt.getText()) && this.organization == null){
        JOptionPane.showMessageDialog(null, "The username has already existed!");
        return;    
        }else if(finduseraccount(this.organization, usernameTxt.getText())){
        JOptionPane.showMessageDialog(null, "The username has already existed!");
        return;    
        }
        
        if(role.equals("Manager")){
            UserAccount manager = organization.getUserAccountDirectory().createUserAccount(this.usernameTxt.getText(), String.valueOf(this.passwordTxt.getPassword()), new ManagerRole());
            manager.setName(this.nameTxt.getText());
            manager.setAge(this.ageTxt.getText());
        }else if(role.equals("HR Manager")){
            UserAccount hrmanager = organization.getUserAccountDirectory().createUserAccount(this.usernameTxt.getText(), String.valueOf(this.passwordTxt.getPassword()), new HRManagerRole());
            hrmanager.setName(this.nameTxt.getText());
            hrmanager.setAge(this.ageTxt.getText());
        }else if(role.equals("Admin")){
            UserAccount admin = organization.getUserAccountDirectory().createUserAccount(this.usernameTxt.getText(), String.valueOf(this.passwordTxt.getPassword()), new AdminRole());
            admin.setName(this.nameTxt.getText());
            admin.setAge(this.ageTxt.getText());
        }else if(role.equals("Drug Admin")){
            UserAccount hrmanager = organization.getUserAccountDirectory().createUserAccount(this.usernameTxt.getText(), String.valueOf(this.passwordTxt.getPassword()), new DrugAdminRole());
            hrmanager.setName(this.nameTxt.getText());
            hrmanager.setAge(this.ageTxt.getText());
        }
        this.usernameTxt.setText("");
        this.passwordTxt.setText("");
        this.nameTxt.setText("");
        this.ageTxt.setText("");
        JOptionPane.showMessageDialog(null, "You have created the useraccount successfully!");
    }//GEN-LAST:event_submitBtnActionPerformed

    // to check if the username exists in the account list
    // system level
     private boolean finduseraccount(EcoSystem system, String username) {
         for(UserAccount useraccount: system.getUserAccountDirectory().getUserAccountList()){
             if(useraccount.getUsername().equals(username)){
                 return true;
             }
         }
         return false;
    }
     
     // organization level
     private boolean finduseraccount(Organization organization, String username) {
         if(organization == null){
             return false;
         }else{
            for(UserAccount useraccount: organization.getUserAccountDirectory().getUserAccountList()){
                if(useraccount.getUsername().equals(username)){
                    return true;
                }
            }
            return false;
         }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ageTxt;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JPasswordField passwordTxt;
    private javax.swing.JButton submitBtn;
    private javax.swing.JTextField usernameTxt;
    // End of variables declaration//GEN-END:variables
}
