/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.HRManagerRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Role.HiredDoctorRole;
import Business.Role.RejectedDoctorRole;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bardw_000
 */
public class HRManagerWorkAreaJPanel extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    private EcoSystem system;

    /**
     * Creates new form HRManagerWorkAreaJPanel
     */
    public HRManagerWorkAreaJPanel(JPanel upc, EcoSystem system) {
        initComponents();
        this.userProcessContainer = upc;
        this.system = system;
        
        populateTable(system);
    }
    
    public void populateTable(EcoSystem system){
        
        DefaultTableModel model = (DefaultTableModel) JTable.getModel();
        
        model.setRowCount(0);
        
        for (UserAccount useraccount : system.getUserAccountDirectory().getUserAccountList()){
            if(useraccount.getDoctoraccount() != null && useraccount.getDoctoraccount().getHired() == false && useraccount.getDoctoraccount().getRejected() == false){
            Object[] row = new Object[6];
            row[0] = useraccount;
            row[1] = useraccount.getAge();
            row[2] = useraccount.getDoctoraccount().getDegree();
            row[3] = useraccount.getDoctoraccount().getYearsofexperience();
            row[4] = useraccount.getEnterprise();
            row[5] = useraccount.getNetwork().getName();
            model.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        hireBtn = new javax.swing.JButton();
        viewDetailBtn = new javax.swing.JButton();
        rejectBtn = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("HR Manager Work Area");

        JTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Age", "Degree", "Years of Experience", "Prefered Enterprise", "Location"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(JTable);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("All the available online doctors in the market");

        hireBtn.setText("Hire");
        hireBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hireBtnActionPerformed(evt);
            }
        });

        viewDetailBtn.setText("View Detail");
        viewDetailBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDetailBtnActionPerformed(evt);
            }
        });

        rejectBtn.setText("Reject");
        rejectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rejectBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 781, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(317, 317, 317)
                        .addComponent(viewDetailBtn)
                        .addGap(18, 18, 18)
                        .addComponent(hireBtn)
                        .addGap(18, 18, 18)
                        .addComponent(rejectBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(309, 309, 309)
                        .addComponent(jLabel1)))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(49, 49, 49)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hireBtn)
                    .addComponent(viewDetailBtn)
                    .addComponent(rejectBtn))
                .addContainerGap(221, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void viewDetailBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDetailBtnActionPerformed
        // TODO add your handling code here:
        int selectRow = this.JTable.getSelectedRow();
        if(selectRow >= 0){
            UserAccount useraccount = (UserAccount) this.JTable.getValueAt(selectRow, 0);
            ViewDoctorDetailJPanel viewDoctorDetailJPanel = new ViewDoctorDetailJPanel(userProcessContainer, system, useraccount);      
            userProcessContainer.add("ViewDoctorDetailJPanel", viewDoctorDetailJPanel);      
            CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
            cardLayout.next(userProcessContainer);
        }else{
            JOptionPane.showMessageDialog(null, "Please select a row from the table first.", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_viewDetailBtnActionPerformed

    private void hireBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hireBtnActionPerformed
        // TODO add your handling code here:
        int selectRow = this.JTable.getSelectedRow();
        if(selectRow >= 0){
            int dialogButton = JOptionPane.YES_NO_CANCEL_OPTION;     
            
            int dialogResult = JOptionPane.showConfirmDialog(null, "Would you like to hire this doctor?", "Warning", dialogButton);
            if(dialogResult == JOptionPane.YES_OPTION){
                UserAccount useraccount = (UserAccount) this.JTable.getValueAt(selectRow, 0);
                useraccount.getDoctoraccount().setHired(Boolean.TRUE);
                useraccount.setRole(new HiredDoctorRole());
                // remove from the system
                this.system.getUserAccountDirectory().getUserAccountList().remove(useraccount);
                // add to the enterprise
                Enterprise enterprise = useraccount.getEnterprise();
                HireStepJPanel hireStepJPanel = new HireStepJPanel(userProcessContainer, system, enterprise, useraccount);      
                userProcessContainer.add("HireStepJPanel", hireStepJPanel);      
                CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
                cardLayout.next(userProcessContainer);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Please select a row from the table first.", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_hireBtnActionPerformed

    private void rejectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rejectBtnActionPerformed
        // TODO add your handling code here:
        int selectRow = this.JTable.getSelectedRow();
        if(selectRow >= 0){
            int dialogButton = JOptionPane.YES_NO_CANCEL_OPTION;     
            
            int dialogResult = JOptionPane.showConfirmDialog(null, "Would you like to reject this doctor", "Warning", dialogButton);
            if(dialogResult == JOptionPane.YES_OPTION){
                UserAccount useraccount = (UserAccount) this.JTable.getValueAt(selectRow, 0);
                useraccount.getDoctoraccount().setRejected(Boolean.TRUE);
                useraccount.setRole(new RejectedDoctorRole());
                JOptionPane.showMessageDialog(null, "This doctor has been rejected.");
                this.populateTable(system);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Please select a row from the table first.", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_rejectBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTable;
    private javax.swing.JButton hireBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton rejectBtn;
    private javax.swing.JButton viewDetailBtn;
    // End of variables declaration//GEN-END:variables
}
